-- ====================================================================
-- SQL SCHEMA FOR CARTE FIDELIS FORM SUBMISSIONS
-- Copy-paste this inside the Supabase SQL Editor to set up your tables
-- ====================================================================

-- 1. Table for Contact Submissions
create table if not exists contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Table for Financing Submissions
create table if not exists financing_submissions (
  id bigint generated by default as identity primary key,
  nom text not null,
  prenom text not null,
  date_naissance text not null,
  ville text not null,
  quartier text not null,
  situation_matrimoniale text not null,
  phone text not null,
  has_local boolean not null,
  amount text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Row Level Security (RLS) Configuration
alter table contact_submissions enable row level security;
alter table financing_submissions enable row level security;

-- 4. Policies for Contact Submissions
create policy "Allow anonymous inserts" on contact_submissions 
  for insert 
  with check (true);

create policy "Allow service_role reads" on contact_submissions 
  for select 
  using (true);

-- 5. Policies for Financing Submissions
create policy "Allow anonymous inserts" on financing_submissions 
  for insert 
  with check (true);

create policy "Allow service_role reads" on financing_submissions 
  for select 
  using (true);
